version: '3.7'

networks:
    wishywish-net:
      driver: bridge

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./backend/db/volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "super-user"
      POSTGRES_PASSWORD: "super-pswd"
      POSTGRES_DB: "wishywish-db"
    networks:
      - wishywish-net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - wishywish-net
# volumes:
#   db_volume:
#   #  external:
#   #      name: backend/db/volum
#      driver: local
#      driver_opts:
#       o: bind
#       type: none
#       device: ./backend/db/volume
